on: [push]
jobs:
  ci:
    runs-on: macos-11
    steps:
      - name: Configure lfs to only check out the files we need, to save on bandwdith
        run: git config --global lfs.fetchinclude 'testdata/**'
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: cargo test
      - run: cargo doc